In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os

In [2]:
path = r'data_movies\TMDB_all_movies.csv'

In [3]:
data_movies = pd.read_csv(path)

In [4]:
data_movies.head()

,id,title,vote_average,vote_count,status,release_date,revenue,runtime,budget,imdb_id,...,spoken_languages,cast,director,director_of_photography,writers,producers,music_composer,imdb_rating,imdb_votes,poster_path
0,2,Ariel,7.100,340.0,Released,1988-10-21,0.0,73.0,0.0,tt0094675,...,suomi,"Eetu Hilkamo, Turo Pajala, Jorma Markkula, Han...",Aki Kaurismäki,Timo Salminen,Aki Kaurismäki,Aki Kaurismäki,NaN,7.4,9011.0,/ojDg0PGvs6R9xYFodRct2kdI6wC.jpg
1,3,Shadows in Paradise,7.300,403.0,Released,1986-10-17,0.0,74.0,0.0,tt0092149,...,"suomi, English, svenska","Haije Alanoja, Aki Kaurismäki, Jukka-Pekka Pal...",Aki Kaurismäki,Timo Salminen,Aki Kaurismäki,Mika Kaurismäki,NaN,7.5,7807.0,/nj01hspawPof0mJmlgfjuLyJuRN.jpg
2,5,Four Rooms,5.858,2672.0,Released,1995-12-09,4257354.0,98.0,4000000.0,tt0113101,...,English,"Lana McKissack, Kathy Griffin, Madonna, Marisa...","Robert Rodriguez, Allison Anders, Alexandre Ro...","Guillermo Navarro, Rodrigo García, Andrzej Sek...","Robert Rodriguez, Quentin Tarantino, Allison A...","Quentin Tarantino, Alexandre Rockwell, Lawrenc...",Combustible Edison,6.7,113599.0,/pyCk5JgtRZwRxnXwfrvyzukaKue.jpg
3,6,Judgment Night,6.500,333.0,Released,1993-10-15,12136938.0,109.0,21000000.0,tt0107286,...,English,"Stephen Dorff, Everlast, Will Zahrn, Emilio Es...",Stephen Hopkins,Peter Levy,"Jere Cunningham, Lewis Colick","Gene Levy, Marilyn Vance, Lloyd Segan",Alan Silvestri,6.6,19707.0,/3rvvpS9YPM5HB2f4HYiNiJVtdam.jpg
4,8,Life in Loops (A Megacities RMX),7.500,27.0,Released,2006-01-01,0.0,80.0,42000.0,tt0825671,...,"English, हिन्दी, 日本語, Pусский, Español",NaN,Timo Novotny,Wolfgang Thaler,"Michael Glawogger, Timo Novotny","Ulrich Gehmacher, Timo Novotny",NaN,8.2,284.0,/7ln81BRnPR2wqxuITZxEciCe1lc.jpg

In [5]:
data_movies.columns

Index(['id', 'title', 'vote_average', 'vote_count', 'status', 'release_date',
       'revenue', 'runtime', 'budget', 'imdb_id', 'original_language',
       'original_title', 'overview', 'popularity', 'tagline', 'genres',
       'production_companies', 'production_countries', 'spoken_languages',
       'cast', 'director', 'director_of_photography', 'writers', 'producers',
       'music_composer', 'imdb_rating', 'imdb_votes', 'poster_path'],
      dtype='object')

In [6]:
### Here we select some relevant columns for our study

features = ['title','imdb_id','overview','cast', 'director', 'vote_average','vote_count', 'imdb_rating','imdb_votes']
df_features = data_movies[features]

In [7]:
df_features

,title,imdb_id,overview,cast,director,vote_average,vote_count,imdb_rating,imdb_votes
0,Ariel,tt0094675,A Finnish man goes to the city to find a job a...,"Eetu Hilkamo, Turo Pajala, Jorma Markkula, Han...",Aki Kaurismäki,7.100,340.0,7.4,9011.0
1,Shadows in Paradise,tt0092149,"Nikander, a rubbish collector and would-be ent...","Haije Alanoja, Aki Kaurismäki, Jukka-Pekka Pal...",Aki Kaurismäki,7.300,403.0,7.5,7807.0
2,Four Rooms,tt0113101,It's Ted the Bellhop's first night on the job....,"Lana McKissack, Kathy Griffin, Madonna, Marisa...","Robert Rodriguez, Allison Anders, Alexandre Ro...",5.858,2672.0,6.7,113599.0
3,Judgment Night,tt0107286,"Four young friends, while taking a shortcut en...","Stephen Dorff, Everlast, Will Zahrn, Emilio Es...",Stephen Hopkins,6.500,333.0,6.6,19707.0
4,Life in Loops (A Megacities RMX),tt0825671,Timo Novotny labels his new project an experim...,NaN,Timo Novotny,7.500,27.0,8.2,284.0
...,...,...,...,...,...,...,...,...,...
1063329,Žatva,NaN,NaN,NaN,NaN,0.000,0.0,NaN,NaN
1063330,Resurrection Fern,NaN,NaN,NaN,NaN,0.000,0.0,NaN,NaN
1063331,Earth Tone Grid,NaN,NaN,NaN,NaN,0.000,0.0,NaN,NaN
1063332,NaN,NaN,NaN,"Johannes Allmayer, Jules Waringo, Vicky Krieps...",Florian Gallenberger,NaN,NaN,NaN,NaN
1063333,NaN,NaN,NaN,"Hailee Steinfeld, Tim Martin Gleason, Holland ...",Travis Knight,NaN,NaN,NaN,NaN

In [8]:
clean_df_features1 = df_features.dropna()
clean_df_features1

,title,imdb_id,overview,cast,director,vote_average,vote_count,imdb_rating,imdb_votes
0,Ariel,tt0094675,A Finnish man goes to the city to find a job a...,"Eetu Hilkamo, Turo Pajala, Jorma Markkula, Han...",Aki Kaurismäki,7.100,340.0,7.4,9011.0
1,Shadows in Paradise,tt0092149,"Nikander, a rubbish collector and would-be ent...","Haije Alanoja, Aki Kaurismäki, Jukka-Pekka Pal...",Aki Kaurismäki,7.300,403.0,7.5,7807.0
2,Four Rooms,tt0113101,It's Ted the Bellhop's first night on the job....,"Lana McKissack, Kathy Griffin, Madonna, Marisa...","Robert Rodriguez, Allison Anders, Alexandre Ro...",5.858,2672.0,6.7,113599.0
3,Judgment Night,tt0107286,"Four young friends, while taking a shortcut en...","Stephen Dorff, Everlast, Will Zahrn, Emilio Es...",Stephen Hopkins,6.500,333.0,6.6,19707.0
6,Star Wars,tt0076759,Princess Leia is captured and held hostage by ...,"Alf Mangan, Grant McCune, Angela Staines, Tiff...",George Lucas,8.200,20921.0,8.6,1496224.0
...,...,...,...,...,...,...,...,...,...
1062993,Intimisto,tt0309718,A woman trapped in her everyday life: a love s...,"Giovanni Lindo Ferretti, Yves Ormond, Jeanne B...",Licia Eminenti,0.000,0.0,7.2,16.0
1062996,night hunters 2025,tt0794986,"The story is about a group called the ""Night H...","Ucha Txelidze, Irakli Odilavadze, Megi Pheradz...",George Lasar,0.000,0.0,7.5,201.0
1063031,Rosina Fumo viene in città... per farsi il cor...,tt0186501,"Rosina, a beautiful and naive girl from Abruzz...","Ewa Aulin, Claudio Gora, Hiram Keller, Fiona F...",Claudio Gora,0.000,0.0,5.7,19.0
1063088,Intezar,tt0233948,Childhood friends Nimmi and Saleem are separat...,"Rakhshi, Pervaiz Qateel, Sarwar Sial, Rani Kir...",Masud Pervaiz,0.000,0.0,7.1,21.0
1063153,Under the Whistle of Bullets,tt0237576,Civil war. Residents of the Ukrainian village ...,"Les Serdyuk, Viktor Stepanenko, Leonid Yanovsk...",Borys Shylenko,0.000,0.0,5.0,10.0

In [9]:
clean_df_features1.to_csv('data_movies.csv', index=False)